### ISSUE TITLE
[BUG] log.Panic(0xc0001e3e68, 0x1, 0x1)

### ISSUE THREAD

**Issue by jiannystein** [zu1k/tg-keyword-reply-bot#43]
我用这些命令但是遇到下面的报错
```
Ubuntu 20.04.6 LTS

sudo apt update
sudo apt upgrade
sudo apt install golang-go

go version
go version go1.13.8 linux/amd64

git clone https://github.com/zu1k/tg-keyword-reply-bot.git
cd tg-keyword-reply-bot

go mod tidy
go build -o tgkwbot .

./tgkwbot TOKEN
```
请问老大这个可以怎么解决？
```
goroutine 1 [running]:
log.Panic(0xc0001e3e68, 0x1, 0x1)
        /usr/lib/go-1.13/src/log/log.go:338 +0xac
main.start(0x0, 0x0)
        /root/tg-keyword-reply-bot/main.go:41 +0xcb
main.main()
        /root/tg-keyword-reply-bot/main.go:34 +0x1e0```

**Comment by jiannystein** [comment]
才发现release的readme，终于可以了 我好菜
```
curl -OL https://golang.org/dl/go1.16.7.linux-amd64.tar.gz
sudo tar -C /usr/local -xvf go1.16.7.linux-amd64.tar.gz
sudo nano ~/.profile 加 export PATH=$PATH:/usr/local/go/bin 到最后一行

go version

git clone https://github.com/zu1k/tg-keyword-reply-bot.git
cd tg-keyword-reply-bot/
go build -ldflags "-w -s" -trimpath -o tgbot .
./tgbot -t TOKEN -s 管理员ID
```

**Comment by jiannystein** [comment]
希望大大还会继续更新，机器人陪了我好多年！
